// macOS implementation. Compiled as Objective-C++ with ARC (-fobjc-arc).

#include "Platform.h"

#include <QWindow>

#import <AppKit/AppKit.h>
#import <ApplicationServices/ApplicationServices.h>
#import <Carbon/Carbon.h>
#import <ServiceManagement/ServiceManagement.h>

namespace {

NSRunningApplication* g_previousApp = nil;
NSVisualEffectView* g_effectView = nil;

std::function<void()> g_hotkeyCallback;
EventHotKeyRef g_hotkeyRef = nullptr;
EventHandlerRef g_hotkeyHandler = nullptr;

struct HotkeyDef {
    UInt32 keyCode;
    UInt32 modifiers;
};

// Keep in sync with hotkeyPresets().
HotkeyDef hotkeyFor(int preset)
{
    switch (preset) {
    case 1: return { kVK_Space, optionKey };
    case 2: return { kVK_ANSI_V, controlKey | optionKey };
    default: return { kVK_ANSI_V, cmdKey | shiftKey };
    }
}

OSStatus onHotkey(EventHandlerCallRef, EventRef, void*)
{
    if (g_hotkeyCallback) {
        // Defer: never run app logic inside a Carbon callback.
        auto callback = g_hotkeyCallback;
        dispatch_async(dispatch_get_main_queue(), ^{ callback(); });
    }
    return noErr;
}

bool isSelf(NSRunningApplication* app)
{
    return app && app.processIdentifier == NSProcessInfo.processInfo.processIdentifier;
}

NSImage* roundedMask(CGFloat radius)
{
    const CGFloat edge = 2.0 * radius + 1.0;
    NSImage* mask = [NSImage imageWithSize:NSMakeSize(edge, edge)
                                   flipped:NO
                            drawingHandler:^BOOL(NSRect rect) {
                                [NSColor.blackColor setFill];
                                [[NSBezierPath bezierPathWithRoundedRect:rect xRadius:radius yRadius:radius] fill];
                                return YES;
                            }];
    mask.capInsets = NSEdgeInsetsMake(radius, radius, radius, radius);
    mask.resizingMode = NSImageResizingModeStretch;
    return mask;
}

} // namespace

namespace platform {

qint64 pasteboardChangeCount()
{
    return static_cast<qint64>(NSPasteboard.generalPasteboard.changeCount);
}

bool pasteboardIsConcealed()
{
    // http://nspasteboard.org — markers used by password managers.
    static NSSet<NSString*>* const markers = [NSSet setWithArray:@[
        @"org.nspasteboard.ConcealedType",
        @"org.nspasteboard.TransientType",
        @"org.nspasteboard.AutoGeneratedType",
        @"com.agilebits.onepassword",
        @"com.typeit4me.clipping",
        @"de.petermaurer.TransientPasteboardType",
    ]];
    for (NSPasteboardType type in NSPasteboard.generalPasteboard.types) {
        if ([markers containsObject:type])
            return true;
    }
    return false;
}

AppInfo frontmostApp()
{
    NSRunningApplication* app = NSWorkspace.sharedWorkspace.frontmostApplication;
    if (!app || isSelf(app))
        return {};
    return { QString::fromNSString(app.localizedName ?: @""),
             QString::fromNSString(app.bundleIdentifier ?: @"") };
}

QByteArray appIconPng(const QString& bundleId, int pixelSize)
{
    @autoreleasepool {
        NSURL* url = [NSWorkspace.sharedWorkspace URLForApplicationWithBundleIdentifier:bundleId.toNSString()];
        if (!url)
            return {};
        NSImage* icon = [NSWorkspace.sharedWorkspace iconForFile:url.path];
        if (!icon)
            return {};

        NSBitmapImageRep* rep = [[NSBitmapImageRep alloc]
            initWithBitmapDataPlanes:nullptr
                          pixelsWide:pixelSize
                          pixelsHigh:pixelSize
                       bitsPerSample:8
                     samplesPerPixel:4
                            hasAlpha:YES
                            isPlanar:NO
                      colorSpaceName:NSCalibratedRGBColorSpace
                         bytesPerRow:0
                        bitsPerPixel:0];
        if (!rep)
            return {};
        rep.size = NSMakeSize(pixelSize, pixelSize);

        [NSGraphicsContext saveGraphicsState];
        NSGraphicsContext.currentContext = [NSGraphicsContext graphicsContextWithBitmapImageRep:rep];
        [icon drawInRect:NSMakeRect(0, 0, pixelSize, pixelSize)
                fromRect:NSZeroRect
               operation:NSCompositingOperationCopy
                fraction:1.0];
        [NSGraphicsContext restoreGraphicsState];

        NSData* png = [rep representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
        return png ? QByteArray::fromNSData(png) : QByteArray();
    }
}

void rememberFrontmostApp()
{
    NSRunningApplication* app = NSWorkspace.sharedWorkspace.frontmostApplication;
    if (app && !isSelf(app))
        g_previousApp = app;
}

void restorePreviousApp()
{
    [NSApp hide:nil];
    if (g_previousApp && !g_previousApp.terminated)
        [g_previousApp activateWithOptions:0];
}

void activateSelf()
{
    [NSApp unhide:nil];
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
    // The replacement (-activate) is cooperative and may be refused when the
    // user is in another app; for a hotkey-invoked popup we want focus now.
    [NSApp activateIgnoringOtherApps:YES];
#pragma clang diagnostic pop
    if (@available(macOS 14.0, *))
        [NSApp activate];
}

bool isAccessibilityTrusted(bool promptUser)
{
    if (!promptUser)
        return AXIsProcessTrusted();
    NSDictionary* options = @{ (__bridge NSString*)kAXTrustedCheckOptionPrompt: @YES };
    return AXIsProcessTrustedWithOptions((__bridge CFDictionaryRef)options);
}

void openAccessibilitySettings()
{
    NSURL* url = [NSURL URLWithString:@"x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"];
    [NSWorkspace.sharedWorkspace openURL:url];
}

bool sendPasteKeystroke()
{
    if (!AXIsProcessTrusted())
        return false;

    CGEventSourceRef source = CGEventSourceCreate(kCGEventSourceStateCombinedSessionState);
    CGEventRef down = CGEventCreateKeyboardEvent(source, static_cast<CGKeyCode>(kVK_ANSI_V), true);
    CGEventRef up = CGEventCreateKeyboardEvent(source, static_cast<CGKeyCode>(kVK_ANSI_V), false);
    CGEventSetFlags(down, kCGEventFlagMaskCommand);
    CGEventSetFlags(up, kCGEventFlagMaskCommand);
    CGEventPost(kCGAnnotatedSessionEventTap, down);
    CGEventPost(kCGAnnotatedSessionEventTap, up);
    CFRelease(down);
    CFRelease(up);
    if (source)
        CFRelease(source);
    return true;
}

bool registerGlobalHotkey(int preset, std::function<void()> callback)
{
    g_hotkeyCallback = std::move(callback);

    if (!g_hotkeyHandler) {
        EventTypeSpec spec = { kEventClassKeyboard, kEventHotKeyPressed };
        InstallApplicationEventHandler(&onHotkey, 1, &spec, nullptr, &g_hotkeyHandler);
    }
    if (g_hotkeyRef) {
        UnregisterEventHotKey(g_hotkeyRef);
        g_hotkeyRef = nullptr;
    }

    const HotkeyDef def = hotkeyFor(preset);
    const EventHotKeyID hotkeyId = { 0x434C5354 /* 'CLST' */, 1 };
    const OSStatus status = RegisterEventHotKey(def.keyCode, def.modifiers, hotkeyId,
                                                GetApplicationEventTarget(), 0, &g_hotkeyRef);
    return status == noErr;
}

QStringList hotkeyPresets()
{
    return { QStringLiteral("⌘⇧V"), QStringLiteral("⌥Space"), QStringLiteral("⌃⌥V") };
}

void prepareWindow(QWindow* window, const QRect& card, int radius, bool dark, bool glass)
{
    if (!window)
        return;
    NSView* view = (__bridge NSView*)reinterpret_cast<void*>(window->winId());
    NSWindow* nsWindow = view.window;
    if (!view || !nsWindow)
        return;

    nsWindow.collectionBehavior = NSWindowCollectionBehaviorCanJoinAllSpaces
                                | NSWindowCollectionBehaviorFullScreenAuxiliary;
    nsWindow.opaque = NO;
    nsWindow.backgroundColor = NSColor.clearColor;
    nsWindow.hidesOnDeactivate = NO;

    if (!glass) {
        [g_effectView removeFromSuperview];
        g_effectView = nil;
        nsWindow.hasShadow = NO;   // QML draws its own shadow in this mode
        return;
    }

    // Place a frosted-glass view *behind* Qt's content view, sized to the card.
    NSView* host = view.superview;
    if (!host)
        return;

    if (!g_effectView) {
        g_effectView = [[NSVisualEffectView alloc] initWithFrame:NSZeroRect];
        g_effectView.blendingMode = NSVisualEffectBlendingModeBehindWindow;
        g_effectView.state = NSVisualEffectStateActive;
        g_effectView.material = NSVisualEffectMaterialHUDWindow;
    }
    g_effectView.appearance = [NSAppearance appearanceNamed:dark ? NSAppearanceNameDarkAqua : NSAppearanceNameAqua];
    g_effectView.maskImage = roundedMask(radius);

    const NSRect vf = view.frame;
    const CGFloat y = host.isFlipped ? vf.origin.y + card.y()
                                     : vf.origin.y + (vf.size.height - card.y() - card.height());
    g_effectView.frame = NSMakeRect(vf.origin.x + card.x(), y, card.width(), card.height());

    if (g_effectView.superview != host) {
        [g_effectView removeFromSuperview];
        [host addSubview:g_effectView positioned:NSWindowBelow relativeTo:view];
    }

    // Native shadow follows the alpha of the window content -> hugs the card.
    nsWindow.hasShadow = YES;
    [nsWindow invalidateShadow];
}

void bringToFront(QWindow* window)
{
    if (!window)
        return;
    NSView* view = (__bridge NSView*)reinterpret_cast<void*>(window->winId());
    NSWindow* nsWindow = view.window;
    if (!nsWindow)
        return;

    // Qt::Tool maps to NSPanel, which by default hides as soon as the app is
    // not active. A menu-bar agent is often *not* made active by macOS 14+,
    // so without this the popup flashes and disappears.
    nsWindow.hidesOnDeactivate = NO;
    nsWindow.level = NSFloatingWindowLevel;
    nsWindow.collectionBehavior = NSWindowCollectionBehaviorCanJoinAllSpaces
                                | NSWindowCollectionBehaviorFullScreenAuxiliary;
    activateSelf();
    [nsWindow orderFrontRegardless];
    [nsWindow makeKeyAndOrderFront:nil];
}

bool launchAtLoginEnabled()
{
    if (@available(macOS 13.0, *)) {
        const SMAppServiceStatus st = SMAppService.mainAppService.status;
        return st == SMAppServiceStatusEnabled || st == SMAppServiceStatusRequiresApproval;
    }
    return false;
}

bool setLaunchAtLogin(bool enable, QString* error)
{
    if (@available(macOS 13.0, *)) {
        SMAppService* service = SMAppService.mainAppService;
        NSError* err = nil;
        const BOOL ok = enable ? [service registerAndReturnError:&err]
                               : [service unregisterAndReturnError:&err];
        if (!ok) {
            if (error)
                *error = QString::fromNSString(err.localizedDescription ?: @"unknown error");
            return false;
        }
        if (enable && service.status == SMAppServiceStatusRequiresApproval) {
            // User switched the item off earlier: macOS wants explicit consent.
            [SMAppService openSystemSettingsLoginItems];
            if (error)
                *error = QStringLiteral("Подтверди ClipStash в «Объектах входа»");
        }
        return true;
    }
    if (error)
        *error = QStringLiteral("Нужна macOS 13 или новее");
    return false;
}

} // namespace platform
